### ISSUE TITLE
Details about GPU run times in Table 2 of the paper

### ISSUE THREAD

**Issue by peri044** [facebookresearch/OctConv#4]
Hello @cypw. First of all, thanks to your amazing research. I had a question regarding Table 2 in your paper. This is not an issue but rather a follow up question. You reported CPU inference times of Resnet-50 for various values of alpha. I'm wondering if you had observed a similar trend of decreasing run times on GPU ?
I've replicated your implementation in Tensorflow and here are my inference times on 2080Ti for Resnet-50 imagenet model. Image size 224x224x3 

alpha | GPU runtime (ms)
------------ | -------------
0 | 13.7
0.125 | 22.8
0.25 | 23.1
0.5 | 23.8
0.75 | 22.6

From the above table, octave convolution performance that I get is worse on GPU.
Did you see a similar performance on GPU from your side? Does this suggest that Octave convolution improvement is more suitable for CPU rather than GPU?

Thank you !!

**Comment by antinucleon** [comment]
According to https://github.com/koshian2/OctConv-TFKeras experiment he observed good speed up on both GPU and CPU. I don't have time to optimize CUDA version but I think at least it will be significantly better if you try to compile with AutoTVM rather than directly run with TF.

**Comment by peri044** [comment]
Thanks @antinucleon. I took a look at his experiment with Cifar-10 Wide ResNet (32x32x3) which is why I got confused when I wasn't observing such trend. I'm using TF 1.13 and cuda-10.0. Thank you for pointing out TVM. I will look into it for a better comparison.

**Comment by antinucleon** [comment]
For AutoTVM you can start from: https://docs.tvm.ai/tutorials/autotvm/tune_relay_cuda.html#sphx-glr-tutorials-autotvm-tune-relay-cuda-py

**Comment by miguelvr** [comment]
It is relevant to know if the paper relies on TVM to make it faster.

**Comment by antinucleon** [comment]
@miguelvr TVM is an automatic way to generate fast kernels. We can also hand write code to achieve theoretical speed up too. So actually it is not about DL framework / compiler, it is about how to get fast code for kernels which is not well optimized by vendor lib today (Usually written by perf experts) such as MKLDNN, CUDNN etc.

**Comment by miguelvr** [comment]
> @miguelvr TVM is an automatic way to generate fast kernels. We can also hand write code to achieve theoretical speed up too. So actually it is not about DL framework / compiler, it is about how to get fast code for kernels which is not well optimized by vendor lib today (Usually written by perf experts) such as MKLDNN, CUDNN etc.

I know what it is. I am facing this issue on my own implementation of OctConv in pytorch.

But my benchmarks show that the OctConv2d op on its own is much faster (4-6x) than a regular convolution, but the the OctResNet models are about 3x slower than the vanilla counterpart.

**Comment by antinucleon** [comment]
@miguelvr There are many reasons to effect end to end perf with a framework aside of operator quality, eg dynamic graph / static graph, multi-stream executor quality and so on. When we have bandwidth we can tune with TVM CUDA to get desirable speed.
