### ISSUE TITLE
Hi, I want to re-implement the result on ImageNet. Where can I get the hyperparameters, ie. batch_size.

### ISSUE THREAD

**Issue by vMagina** [facebookresearch/OctConv#8]

**Comment by cypw** [comment]
Our [train_imagenet.py](https://github.com/facebookresearch/OctConv/blob/master/utils/gluon/train_imagenet.py) is based on the one released by Gluon-CV, where the training scripts (hyper-params) can be found at https://gluon-cv.mxnet.io/model_zoo/classification.html .
